### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by dbaroncelli** [joreilly/BikeShare#1]
Hi John,

I don't seem to be able to compile the project.

<img width="1285" alt="Schermata 2020-08-05 alle 19 54 55" src="https://user-images.githubusercontent.com/5320104/89447009-9b8b2180-d755-11ea-86ce-3495985ea239.png">

**Comment by joreilly** [comment]
I've seen this happen in recent versions of AS.....sometimes invalidate cache seems to "fix" but should still be possible to run app.....do you also get issue if you try that?

**Comment by joreilly** [comment]
One other thing to note right now, if you can run app, is that api is currently down (https://api.citybik.es/v2/networks)

**Comment by dbaroncelli** [comment]
Hi John,

you are actually right

<img width="1024" alt="Schermata 2020-08-05 alle 20 04 10" src="https://user-images.githubusercontent.com/5320104/89447833-f2ddc180-d756-11ea-8c67-fe41cc894c5f.png">

**Comment by joreilly** [comment]
I didn't get chance to do it for initial version but have a TODO to use some kind of `Result` type and cater for errors like this.
